USE [DB211708020]
GO

/****** Object:  Table [dbo].[f_checkoutsystem]    Script Date: 4/20/2022 8:59:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[f_checkoutsystem](
	[CSID] [char](2) NOT NULL,
	[CSystem] [varchar](125) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[f_layout](
	[LayoutID] [char](1) NOT NULL,
	[LayoutDesc] [varchar](125) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LayoutID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[f_store](
	[StoreID] [char](2) NOT NULL,
	[StoreSize] [int] NOT NULL,
	[CSID] [char](2) NOT NULL,
	[LayoutID] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[StoreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[f_store]  WITH CHECK ADD FOREIGN KEY([CSID])
REFERENCES [dbo].[f_checkoutsystem] ([CSID])
GO

ALTER TABLE [dbo].[f_store]  WITH CHECK ADD FOREIGN KEY([LayoutID])
REFERENCES [dbo].[f_layout] ([LayoutID])
GO
